### ISSUE TITLE
General Map Functions

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats-National#10]
- [x] Scale
- [x] Pan/zoom
- [x] Show Your Location - This tool will cause the map to redraw centered on the user’s location, with a blue dot shown at the user’s location (primarily for mobile devices). 
- [x] Basemap Selection
- [x] Geosearch

Note that some of these map functions may be moved to a "Topography" section, and/or may need separate issues :)

**Comment by USGSPMM3** [comment]
I would like to see the NHDPlusV2 flowlines as a display option similar to how they're being displayed in the test delineation tools (https://test.streamstats.usgs.gov/nldi-delineate). 
We may need to turn our existing VAA table for TOT into a relational database so we can get flowlines and attributes.
![image](https://user-images.githubusercontent.com/16928289/109992930-ffb09c80-7cc8-11eb-9ae6-7543be9d2718.png)

**Comment by amedenblik** [comment]
Moved to separate issues:
- [Measure tool](https://github.com/USGS-WiM/StreamStats-National/issues/51)
- [Elevation tool](https://github.com/USGS-WiM/StreamStats-National/issues/52)

**Comment by amedenblik** [comment]
Moved to separate issues:

- [Add flowlines](https://github.com/USGS-WiM/StreamStats-National/issues/69)
- [Add other toggleable layers](https://github.com/USGS-WiM/StreamStats-National/issues/70)
