### ISSUE TITLE
Update geolocation

### ISSUE THREAD

**Issue by mitchas** [USGS-WiM/StreamStats-National#104]
Geolocation can take a few seconds to load. 
We should add some kind of indicator so people know that something is happening.

**Comment by amedenblik** [comment]
- [ ] Move icon to map
- [ ] Add loading indicator (maybe change button to spinner? smaller load screen than full-page)

**Comment by harper-wavra** [comment]
Combined with https://github.com/USGS-WiM/StreamStats-National/issues/237
