### ISSUE TITLE
Add gages to Fire Hydrology - Query by Fire Perimeter workflow 

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats-National#114]
- [x] Grab streamgages from the service response-- must complete https://github.com/USGS-WiM/nldi_polygon_query/issues/5 first
- [x] Display the gages on the map: they already exist on the map, so maybe change symbology? and reset symbology when workflow is complete
- [x] List the gages in the report

**Comment by USGSPMM3** [comment]
If/when we add these services we may also want to determine which gages are active and in the fire boundary as potential gaes that could have burned. 

At some point we would like to have a application gage filter for active/discontinued

**Comment by amedenblik** [comment]
This is currently a medium priority issue within the StreamStats ecosystem.

* The current Fire Hydrology - Query by Fire Perimeters returns NLDI data that can be linked to the active NWIS stream gages via NLDI services: https://waterdata.usgs.gov/blog/nldi-intro/ 
* Time of Travel (https://github.com/USGS-WiM/traveltime) also returns gages related to NLDI & says whether they are active or not

**Comment by amedenblik** [comment]
New service endpoint is available: https://nldi-polygon-query.streamstats.usgs.gov/docs#/default/query_poly_nldi_poly_query_new__post
