### ISSUE TITLE
Query by Fire Perimeters Issue

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats-National#133]
When using the Query by Fire Perimeters workflow, we are getting CORS errors. 

![image](https://user-images.githubusercontent.com/59063181/150172045-33ee1def-1045-42bb-bcdc-a38ab66713f5.png)

**Comment by amedenblik** [comment]
Issue resolved by SysOps by restarting the FireHydroServer EC2 instance and restarting the daemon. Issue was caused by system updated.
