### ISSUE TITLE
SD Delineation outside pour point

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats-National#148]
Delineation at point in  44.70168, -97.02516 looks a bit wonky:

![image](https://user-images.githubusercontent.com/12058013/157085199-794f6551-4689-454b-bf9b-a2b05869ea13.png)

**Comment by harper-wavra** [comment]
This seems to have been fixed.
![image](https://user-images.githubusercontent.com/59063181/200583911-946e36a3-8a33-4214-a771-f88f448fad21.png)
