### ISSUE TITLE
Zoom issue on Safari on MacOS

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats-National#154]
For Beta release #128 

As you zoom into the map using the + and - buttons on Safari on MacOS, the buttons disappear and then the map scale disappears. You can still click the buttons, but they are hidden.

![image](https://user-images.githubusercontent.com/40237491/163839078-19f59f00-7777-4096-b83e-913cbe968853.png)

**Comment by ChadFanguy-usgs** [comment]
setOverlayLayer function and overlay.visible may be having unexpected behavior causing this on Safari on MacOS.

**Comment by ChadFanguy-usgs** [comment]
Very inconsistent, may be a JavaScript loading issue and nothing we can do about it.

**Comment by amedenblik** [comment]
Won't fix
