### ISSUE TITLE
Fire pop-ups appear even if layer is turned off

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats-National#196]
Steps to recreate:

1. Select the Fire Hydrology workflow
2. Select "Query by Fire Perimeters"
3. Find a fire that is visible on both a "XXXX Wildland Fire Perimeters" layer and the MTBS Fire Boundaries layer
4. Turn off the MTBS fire layer
5. Click on the fire 

The MTBS Fire Boundaries pop-up appears, even though that layer is turned off:
[image](https://user-images.githubusercontent.com/40237491/175612207-c63bce05-7231-4b5a-b530-32281d312536.png)

**Comment by amedenblik** [comment]
See #235 for related issue: 

> Also, in this screen shot below, I had turned off the MTBS Fire boundaries in an attempt to use the Wildland Fire Boundaries but the tool still selected the MTBS first. Probably shouldn't be able to query layers that are turned off.

**Comment by harper-wavra** [comment]
Completing in https://github.com/USGS-WiM/StreamStats-National/issues/235
