### ISSUE TITLE
Release v1.2.0-beta 

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats-National#203]
Once 

- [x] https://github.com/USGS-WiM/StreamStats-National/pull/202 is merged 
- [x] Kitty clicks publish on https://www.sciencebase.gov/catalog/item/60e5a8e7d34e2a7685cf3f33 in SB 
- [x] https://github.com/USGS-WiM/StreamStats-National/issues/204 is completed,

we should push to master and create a new release.

- [x] Update version numbers in the code https://github.com/USGS-WiM/StreamStats-National/pull/212
- [x] Update CHANGELOG.md with all PR since last release https://github.com/USGS-WiM/StreamStats-National/pull/212
- [x] Pull request this branch -> dev -> staging -> master
#212 
#213 
#214
- [x] Create release in Github with new version number https://github.com/USGS-WiM/StreamStats-National/releases/tag/v1.2.0-beta

**Comment by amedenblik** [comment]
We are currently on v1.1.1-beta, so I think the next version should be v1.2.0-beta since the patch number resets
