### ISSUE TITLE
Network Trace from fire perimeter includes catchments

### ISSUE THREAD

**Issue by USGSPMM3** [USGS-WiM/StreamStats-National#207]
I think we should exclude catchments, or at minimum change the display for catchments to a different color as they are the same as streams. 

![Capture](https://user-images.githubusercontent.com/16928289/178318840-8f77c232-d3d7-44f9-998c-30048fb0b30e.PNG)

**Comment by harper-wavra** [comment]
Don't display the catchment if it is returned. 
![image](https://user-images.githubusercontent.com/59063181/178321393-40e05737-460f-4ca6-bf68-7563c73bb042.png)
