### ISSUE TITLE
Regulation

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats-National#21]
Determine basin characteristics for “unregulated” portion of the basin (returning Colorado functionality, but make national) 

- Feature Description: Tests for the presence of upstream regulation from dams 
- Inputs: watershed, crs output, ...?

**Comment by USGSPMM3** [comment]
Needs SSHydro. But in level 2 effort to add dams and perform simple computations we might want to "split" the polygon into 2 features

**Comment by harper-wavra** [comment]
Closing in favor of https://github.com/USGS-WiM/StreamStats-National/issues/30
