### ISSUE TITLE
Precomputed Basin Characteristics using lambda

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats-National#22]
Query lambda services for pre-computed basin characteristics 

See Theo's white paper?

**Comment by amedenblik** [comment]
Roll in Bieger and Channel width that are in US_National region

**Comment by amedenblik** [comment]
Finish out issue #57 (step #6) with this issue. We are waiting for lambda services to be functional.

**Comment by amedenblik** [comment]
Per @USGSPMM3: this should be added as part of the Delineation workflow
