### ISSUE TITLE
Check BCs

### ISSUE THREAD

**Issue by USGSPMM3** [USGS-WiM/StreamStats-National#231]
I selected a point in MT where I don't think we actually have this precip grid, yet it comes back with a value. Need to evaluate the stats. 

46.28546, -111.48626

![image](https://user-images.githubusercontent.com/16928289/196296829-1f96936c-c829-43b0-8f29-b3da61f86003.png)

![image](https://user-images.githubusercontent.com/16928289/196296879-149efb87-5ff4-4a07-98d9-c9d0df4ab30b.png)

**Comment by harper-wavra** [comment]
This PR might be helpful as it does something similar https://github.com/USGS-WiM/StreamStats-National/pull/249
