### ISSUE TITLE
NLDI generalization of basin boundary

### ISSUE THREAD

**Issue by USGSPMM3** [USGS-WiM/StreamStats-National#232]
The basin boundaries from NLDI appear to be very generalized. We need to investigate these. At one point Blodgett indicated we could get the non-generalized version.

**Comment by harper-wavra** [comment]
@Anders-Hopkins do you know if there is a way to get the non-generalized boundary? 

We are using https://nhgf.wim.usgs.gov/processes/nldi-splitcatchment/jobs?response=document which doesn't seem to have that option. But maybe there is a different endpoint we should be using?

**Comment by Anders-Hopkins** [comment]
@harper-wavra There is some simplification that happens in the NLDI_Flowtools. This is done because there are often splinters and or small polygons which get created when the 'upstream_basin' is created. I'm not sure if there is an elegant way to get around this, other than to make requests directly to the NLDI for specific catchments.

**Comment by Anders-Hopkins** [comment]
Downloaded a NHD dataset and plotted it against polygons returned from NLDI. The red polygon is a catchment from the NLDI (huc16 maybe). The blue polygon is a HUC12 from NHD (this was the smallest huc size included in the download). While the blue polygon covers a much bigger area, the red polygon from NLDI seems to be somewhat simplified by comparison.
 
![image](https://user-images.githubusercontent.com/55411265/208782693-230f0847-3302-4ceb-858d-ed4037344217.png)

**Comment by Anders-Hopkins** [comment]
After further digging, the [NLDI catchment](https://waterdata.usgs.gov/blog/nldi-intro/) are derived from [NHDPlus V2](https://nhdplus.com/NHDPlus/) catchments. I downloaded NHDPlus V2 catchments from [here](https://www.epa.gov/waterdata/nhdplus-upper-mississippi-data-vector-processing-unit-07) and found them to be polygons derived from raster data. Depending on the methodology of how these rasters zones were simplified into polygons would explain why basin boundaries created from the NLDI appear to be more generalized than those from streamstats. 
![image](https://user-images.githubusercontent.com/55411265/208788634-55260b85-e2f2-4b81-af43-fdd328396c8a.png)

**Comment by amedenblik** [comment]
Update from Anders / Dave Blodgett: there are some options for simplifying with some endpoints https://labs.waterdata.usgs.gov/api/nldi/linked-data/nwissite/USGS-02367310/basin?f=json&simplify=false&splitCatchment=false

We will continue looking into this

**Comment by Anders-Hopkins** [comment]
After comparing the simplified vs non-simplified upstream basin geometries, the differences are not incredibly significant. I have nldi-flowtools requesting non-simplified geometries and I have reduced the amount of geometry simplification that occurs in a merging function within the nldi-flowtools. This helps the returned upstream geometry to retain approximately 25% more vertices in one test delineation, but when viewed on a web map, I would say these changes are marginal at best. However, this is the utmost that can be done, without there being multipolygon splinter geometries included in the outputs. Currently, I am updating some dependencies and tests and will deploy these changes as soon as I can.

**Comment by amedenblik** [comment]
Closing this for now. @USGSPMM3 let us know if you'd like further discussion. Anders has updated the NLDI flow tools to perform less generalization on basin boundaries, which will hopefully be deployed this week, but the differences are not major.
