### ISSUE TITLE
Workflow for adding a second fire perimeter

### ISSUE THREAD

**Issue by USGSPMM3** [USGS-WiM/StreamStats-National#233]
While playing around it appeared I was able to add another fire perimeter every time I selected a new perimeter and it added more. However, after working all the way through and then looking at "Overview" I could only see the first of the fire traces.  

![image](https://user-images.githubusercontent.com/16928289/196298028-b1e2d424-b2e5-4a08-bc64-28b3c7bd9822.png)
 
![image](https://user-images.githubusercontent.com/16928289/196298175-098087a5-504e-456a-816c-05233850600c.png)

**Comment by harper-wavra** [comment]
added to https://github.com/USGS-WiM/StreamStats-National/issues/235
