### ISSUE TITLE
Overview and print summary

### ISSUE THREAD

**Issue by USGSPMM3** [USGS-WiM/StreamStats-National#234]
- [x] Overview button shows items in the report. Probably should say "View Report" instead?

- [x] ~~Print report button needs and "x" in the upper right corner.~~ -added to https://github.com/USGS-WiM/StreamStats-National/issues/241

- [x] ~~Even though I have a scenario in the report, it doesn't show up in the Print Summary or in the print preview when I select print.~~ added issue https://github.com/USGS-WiM/StreamStats-National/issues/247
![image](https://user-images.githubusercontent.com/16928289/196298440-b4097a4a-97dc-4918-8202-9c8971d71525.png)

**Comment by amedenblik** [comment]
Additional comment from @chaqazarad: should we stick the "Close Window" and "Print" buttons at the bottom of the pop-up window?

![image](https://user-images.githubusercontent.com/40237491/196524763-668e3a77-c2d9-430a-ab06-4854ca5c3ff5.png)

**Comment by chaqazarad** [comment]
@harper-wavra The blank print summary occurs, if you don't click a delineation point.
![image](https://user-images.githubusercontent.com/85179214/200938567-41e16071-3fc5-4d80-bc42-978162c0592a.png)

![image](https://user-images.githubusercontent.com/85179214/200938597-7a0dce68-44a6-435b-a144-af9809e35475.png)

**Comment by chaqazarad** [comment]
I think if you don't click a point for the fire hydrology it just gets hung up and doesn't complete to the next step (infinite loading). Wondering if we need better shoe horning to make sure users don't do weird stuff.  Maybe disable next button until they have "selected" a delineation point?

**Comment by harper-wavra** [comment]
Thanks! That is exactly what I am thinking - I created an issue for that here https://github.com/USGS-WiM/StreamStats-National/issues/247
