### ISSUE TITLE
Query by Fire Perimeter Issues

### ISSUE THREAD

**Issue by USGSPMM3** [USGS-WiM/StreamStats-National#235]
- [ ] When trying to find and select a fire perimeter the user does not have any information until after the perimeter is selected and then it can't be "unselected".  The fire information popup needs a "select this fire" and if the "x" is chosen, that fire perimeter should be de-selected. 

- [x] Also, in this screen shot below, I had turned off the MTBS Fire boundaries in an attempt to use the Wildland Fire Boundaries, but the tool still selected the MTBS first. Probably shouldn't be able to query layers that are turned off. 
[example](https://user-images.githubusercontent.com/16928289/196298839-7a69fd9e-14d2-4e75-b8e8-4085279d05e2.png)

- [ ] While playing around it appeared I was able to add another fire perimeter every time I selected a new perimeter and it added more. However, after working all the way through and then looking at "Overview" I could only see the first of the fire traces. We should make it so you can only select one fire perimeter per workflow selection. The following screen shot shows where I selected multiple fire perimeters to find the one I was looking for and then it traced all of them.
[example](https://user-images.githubusercontent.com/16928289/196299126-411937b7-99e8-4c67-963b-f44b52931a44.png)
[example](https://user-images.githubusercontent.com/16928289/196298028-b1e2d424-b2e5-4a08-bc64-28b3c7bd9822.png)
[example](https://user-images.githubusercontent.com/16928289/196298175-098087a5-504e-456a-816c-05233850600c.png)

**Comment by harper-wavra** [comment]
Last item related to https://github.com/USGS-WiM/StreamStats-National/issues/196. Should be able to complete both issues at the same time.
