### ISSUE TITLE
Map doesn't load in space where sidebar is closed

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats-National#236]
Occasionally, after collapsing the sidebar, the map is not loaded in the space where the sidebar was

![image](https://user-images.githubusercontent.com/40237491/196517799-1b30a679-68f2-4989-b9c6-5a18aa020c4c.png)

**Comment by harper-wavra** [comment]
@mitchas Do you think you'd have time to take a look at this issue also?
