### ISSUE TITLE
Additional workflows aren't showing details

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats-National#240]
I wasn't able to recreate this issue, but @chaqazarad found that additional workflow details aren't showing in the Overview tab:

![image](https://user-images.githubusercontent.com/40237491/196524473-d451e086-c42c-494a-ad31-dfc9ce1d2205.png)

**Comment by amedenblik** [comment]
@chaqazarad Are you able to provide steps to recreate this issue? I haven't been able to recreate it.

**Comment by chaqazarad** [comment]
I believe its the same issue where if you complete a workflow without selecting a delineation point then it messes things up.

**Comment by amedenblik** [comment]
Thanks! Closing in favor of #247 (and possible #246).
