### ISSUE TITLE
Streamgages

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats-National#27]
Plot streamgages (NWIS or StreamStats lat/long) 

We can use the gagestats services for this. The endpoint to query gages by a bounding box is almost ready for the test site (Edit: this is now live on production)

- Click streamgage and have options for: 
    - Show basic information  
        -  - [x] Name and ID can be on a single line as a header 
        -  - [x] Lat/long? Maybe remove....not sure if needed on a map application 
        -  - [x] Most recent value (similar to water dashboard) 
    -  - [x] StreamStats gage page  
    - - [x] NWIS 
    - Hybrid (proposed functionality similar to waterwatch) 
        - - [ ] Plot hydrograph from NWIS with statistics from streamstats gage page 
- Return old gage header information currently only available in USGS internal page (name ?)

**Comment by USGSPMM3** [comment]
Mostly level 1, the hybrid is likely a level 2 but we should check in with NWIS/WaterWatch to see what they're doing
