### ISSUE TITLE
Create Template Components

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats-National#4]
We should create basic templates for the app functions/workflows. We'll need to think about:

- [x] Where the functions are called - e.g. in the top or bottom of sidebar, if it's contained within a button group or within a popup from that, etc.

- [ ] What the workflow of that tool looks like - Are there multiple steps? Do we need a modal or display in bottom bar with the option to expand?

- [ ] URL params - should we work this in to each component or just add them in as it comes?

- [ ] Report card - each component will be hooked up to a card in the sidebar for displaying in the report

- [ ] User guide elements - it may be helpful to automate the user guide a bit by building a user guide portion for each element and hooking that up to the user guide? Is that too much? Or maybe the user guide can be more of an overview since we'll have step-by-step workflows?

- [x] Would a config file be useful? Maybe to set the Title, Icon, Base URL, URL Params, User guide elements, hookups, etc. and plug it into the template? We can use Angular inputs/outputs for this https://angular.io/guide/inputs-outputs 

Some of these might not need to be involved in a template or might be broken out into multiple types of templates, but having automatic hookups in place will help with adding new functionality

[Wireframe-Idea-7.pdf](https://doimspp.sharepoint.com/sites/StreamStatsTeam/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=a4JN8V&CT=1612800046627&OR=OWA%2DNT&CID=d1a4687d%2D8bd1%2De0f6%2D0e4a%2D9810035cf1ec&FolderCTID=0x0120001859A4672AAD7245ACDDA6C82EB5F284&id=%2Fsites%2FStreamStatsTeam%2FShared%20Documents%2FSS%5FTeamSpace%2FNational%20Application%2FSS%20National%20Interface%20Planning%2FWireframe%2DIdea%2D7%2Epdf&parent=%2Fsites%2FStreamStatsTeam%2FShared%20Documents%2FSS%5FTeamSpace%2FNational%20Application%2FSS%20National%20Interface%20Planning)

**Comment by amedenblik** [comment]
Breaking remaining items into new issues:

- URL parameters: issue #90  
- User guide: issue #91
