### ISSUE TITLE
First Function - Delineation Using NLDI

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats-National#5]
Our first step is incorporating delineation in to make sure our ideas will actually work 😅 

There is a test site for the NLDI split catchment delineation here: http://test.streamstats.usgs.gov.s3-website-us-east-1.amazonaws.com/nldi-delineate/?lat=42.92118774382267&lng=-92.54093170166017. If you open the network tab, filter by "jobs?response=document" and delineate, you can see the inputs/outputs expected once the split catchment functionality is live.

**Comment by kjacobsen16** [comment]
Notes from feature list:
This feature uses NLDI services to return a delineation based on a user click point. This feature is enabled for the national StreamStats region/application 

- Inputs: lat/long of clickpoint and other inputs needed by NLDI service (type of return?) 

- Outputs: Returns a geojson of the delineated basin 
- Proposed Method(s): Pull lat/long from user, add other necessary inputs for NLDI service and call service. Returns geojson of basin delineation. We need to

**Comment by kjacobsen16** [comment]
Make a post request to this url: https://nhgf.wim.usgs.gov/processes/nldi-splitcatchment/jobs?response=document
```
{
	"inputs": [
		{
			"id": "lat",
			"type": "text/plain",
			"value": "45"
		},
		{
			"id": "lng",
			"type": "text/plain",
			"value": "-93"
		},
		{
			"id": "upstream",
			"type": "text/plain",
			"value": "False"
		}
	]
}
```
The 'upstream' variable can be either True or False. True will return everything upstream from the input point. False will split the local catchment at the point and only return the split portion of the local catchment.

**Comment by HansVraga** [comment]
Slight change in direction - going to build an example form to focus on getting the StreamStats workflow framework down, then focusing on delineation (this issue). @ltmetz
