### ISSUE TITLE
Set Up Fire Hydrology Workflow

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats-National#56]
- [x] Add Fire Hydrology to the Workflows
- [x] Once Fire Hydrology is selected, display the burn layers:
    - [x] Active WildFire Perimeters https://services3.arcgis.com/T4QMspbfLg3qTGWY/ArcGIS/rest/services/Public_Wildfire_Perimeters_View/FeatureServer/0
    - [x] Archived WildFire Perimeters: https://services3.arcgis.com/T4QMspbfLg3qTGWY/ArcGIS/rest/services/Interagency_Fire_Perimeter_History_All_Years_Read_Only/FeatureServer/0
    - [x] MTBS Fire Boundaries: https://apps.fs.usda.gov/arcx/rest/services/EDW/EDW_MTBS_01/MapServer
    - [x] Burn Severity: https://apps.fs.usda.gov/arcx/rest/services/RDW_Wildfire/MTBS_CONUS/MapServer
    

- [x] I think from there users can select one or more of the following: (set up the workflow)
     - [x] 1. Calculate Fire Hydrology for a basin
    a. This will be a separate issue, but this is essentially to delineate a basin, and calculate percent burned area and compute fire hydrology equations for that basin #57 
     - [x] 2. Trace Downstream from a fire perimeter and find gages #58

**Comment by kjacobsen16** [comment]
@USGSPMM3 are those bottom steps correct for future implementation? Users will either compute fire hydrology for a basin _or_ run the trace tool on a selected fire perimeter like in the demo app?

**Comment by amedenblik** [comment]
Active wildfire perimeters layer has updated: https://services3.arcgis.com/T4QMspbfLg3qTGWY/arcgis/rest/services/Current_WildlandFire_Perimeters/FeatureServer/0/query?outFields=*&where=1%3D1
