### ISSUE TITLE
Calculate Fire Hydrology for a basin

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats-National#57]
This is part of the "Fire Hydrology" workflow. If a user chooses to calculate the fire hydrology for a basin, we will have the following steps:
1. Prompt user for a click point
2. Run an NLDI delineation on the click point
3. Prompt user for years to use for burned area calculation 
4. Calculate % burned area of basin
5. Query NSS for the "US_National" equations "Burned Area Flow Statistics" equations to find out which basin characteristics are needed
6. Compute basin characteristics for those equations
    a. this will require use of the lambda services (I30 precip value, Jan max/min temps, % forest, etc.) and querying from a map service (surficial geology - https://www.sciencebase.gov/arcgis/rest/services/Catalog/5888bf4fe4b05ccb964bab9d/MapServer/identify )
7. Solve the NSS equations using the basin chars

#4 is already being done in the [SS national demo](https://github.com/USGS-WiM/SSNationalDemo/blob/fireHydrology/src/app/modules/core/components/map/map.component.ts#L247) app using a combination of map service queries and Turfjs functions. That functionality can be replicated for this step.

To test the functionality, see the [demo app](https://test.streamstats.usgs.gov/fire-hydro-demo/)

**Comment by harper-wavra** [comment]
From KJs [notes](https://doimspp.sharepoint.com/sites/GS-UMidWIM/_layouts/15/Doc.aspx?sourcedoc={86ee3545-8271-46a1-b16f-158b12f19ba3}&action=edit&wd=target%28Introduction.one%7Cfa6d5c1d-d7fb-4d35-b339-992ef3438208%2FFire%20Hydro%7C76d1a4db-6c56-41b9-a79c-f38ba7e1d86d%2F%29):
![image](https://user-images.githubusercontent.com/59063181/134383803-10e6976f-0e99-4b44-b047-22b29daa98f3.png)

**Comment by amedenblik** [comment]
Updated instructions:

1. Prompt user for click point
2. Delineate the basin from that click point using NLDI
3. Prompt user for range of years to use for burned area calculation
4. Calculate % of area burned by range of years
5. Compute basin characteristics:
     - I30 precipitation value:
          - The files are published here: https://www.sciencebase.gov/catalog/item/60bfcc77d34e86b938917575
          - Need to get these in lambda service
          - Access the values via lambda service
     - Surficial geology:
          - Service is here: https://www.sciencebase.gov/arcgis/rest/services/Catalog/5888bf4fe4b05ccb964bab9d/MapServer/identify
          - Compute this similarly to % Burned Area 
     - January min/max temps:
          - The files will be published here: https://www.sciencebase.gov/catalog/item/60d9ce4fd34e5831aff8a430
          - Need to get these in lambda service
          - Access the values via lambda service
     - % Forest
          - Use lc1 + lc2 + lc3 + lc4 + lc5 + lc6 in the lambda services (these are all the forest landcover classes in the lambda services)
     - Annual precipitation:
          - Use prcp in lambda service
     - Basin slope
          - Use slope in the lambda service
6. Solve NSS equations for flow estimates:
     - The equations are already in NSS
     - Only do "Level 1 equations", not level 2 or 3 yet: see page 26-27 for the Level 1 equations https://pubs.usgs.gov/sir/2011/5236/report/SIR11-5236.pdf
     - I used this link to figure out the parameters needed, but some of these parameters (Change_in_Normalized_Burn_Ratio and Hydraulic_Functional_Connectivity) are needed for Level 2 or 3 equations so we don't need them https://streamstats.usgs.gov/nssservices/scenarios?regions=74&statisticgroups=39

Lambda services documentation: https://code.usgs.gov/StreamStats/cogQuery/lambdas/cq-lambda
Example query: https://test.streamstats.usgs.gov/gridqueryservices?latitude=43.141572&longitude=-109.717418

**Comment by amedenblik** [comment]
Lambda service is now working for I30 precipitation, January min temperatures, and January max temperatures. Examples:

January max temp: https://hgst52v4o1.execute-api.us-east-2.amazonaws.com/cogQuery?latitude=33.9832&longitude=-118.1365&fcpg_parameter=jantmax
	
January min temp: https://hgst52v4o1.execute-api.us-east-2.amazonaws.com/cogQuery?latitude=33.9832&longitude=-118.1365&fcpg_parameter=jantmin
	
I30: https://hgst52v4o1.execute-api.us-east-2.amazonaws.com/cogQuery?latitude=33.9832&longitude=-118.1365&fcpg_parameter=i2y30

**Comment by amedenblik** [comment]
Steps 6 and 7 cannot be completed due to errors with the lambda service. Closing this issue with Steps #1 through #5 complete. % Geology has also been computed, since this data does not come from the lambda service. 

Step 6 will be completed in issue #22.
Step 7 will be completed in issue #26.
