### ISSUE TITLE
Implement Trace Functionality from National Demo App

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats-National#58]
This is part of the "Fire Hydrology" workflow. If a user chooses to trace downstream from a fire perimeter, we will have the following steps:

- Prompt user to select a fire perimeter
- Highlight the fire perimeter and send it to Taylor's trace service

The National demo application already does this, so we can duplicate the functionality from there. I think it's also supposed to display gages, which it's not currently doing.

Demo app: https://test.streamstats.usgs.gov/fire-hydro-demo/
Repo: https://github.com/USGS-WiM/SSNationalDemo/

**Comment by harper-wavra** [comment]
From KJs [notes](https://doimspp.sharepoint.com/:o:/r/sites/GS-UMidWIM/_layouts/15/WopiFrame.aspx?sourcedoc={86ee3545-8271-46a1-b16f-158b12f19ba3}&action=edit&wd=target%28Introduction%2Eone%7CFA6D5C1D%2DD7FB%2D4D35%2DB339%2D992EF3438208%2F%29onenote%3Ahttps%3A%2F%2Fdoimspp%2Esharepoint%2Ecom%2Fsites%2FGS%2DUMidWIM%2FShared%20Documents%2FProjects%2FStreamstats%20Ecosystem%2FKJ%27s%20Guide%20to%20StreamStats%201%2FIntroduction%2Eone#Fire%20Hydro&section-id={FA6D5C1D-D7FB-4D35-B339-992EF3438208}&page-id={76D1A4DB-6C56-41B9-A79C-F38BA7E1D86D}&end):
![image](https://user-images.githubusercontent.com/59063181/134383578-164913d1-0cf9-4171-8575-77c5340b0f70.png)
