### ISSUE TITLE
Figure out Active Fire Layers

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats-National#60]
> We're getting a number of fires in Montana and I thought I would check out a couple of them on our pilot app and noticed the map services for active fire perimeters are not showing any fires. When I jump to the NIFC pages it looks like they may start a new map service every year for active fires or fires to date in a given year. Thus, we'll need to actively update our web services links every year. Is there anyway to add a reminder in the code to email us to update?

Upon further discussion, we should try to set up the code so it looks for the most recent layer instead

**Comment by kjacobsen16** [comment]
Waiting for Kitty's confirmation but seems like the active fires layer is actually https://services3.arcgis.com/T4QMspbfLg3qTGWY/arcgis/rest/services/Current_WildlandFire_Perimeters/FeatureServer/0/query?outFields=*&where=1%3D1

**Comment by amedenblik** [comment]
Closed with PR #89
